# Generated by Django 2.1.5 on 2019-05-02 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome do comissão')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla ')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Data de Alteração')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('draft', 'Rascunho')], max_length=15)),
            ],
            options={
                'verbose_name': 'Tipo de Categoria',
                'verbose_name_plural': 'Tipo de Categorias',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titulo do Formulário')),
                ('slug', models.SlugField()),
                ('link', models.URLField(max_length=250, verbose_name='Endereço do formulário')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Data de Alteração')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('draft', 'Rascunho')], max_length=15)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.SubCategory')),
            ],
            options={
                'verbose_name': 'Formulário',
                'verbose_name_plural': 'Formulários',
            },
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_image'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Data de Alteração'),
        ),
        migrations.DeleteModel(
            name='SubCategoria',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Category'),
        ),
    ]
